INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10000','Male Open','R');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10000','Male Open','C');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10000','Under 21 Male','R');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10000','Under 21 Male','C');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10001','Male Open','B');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10001','Female Open','R');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10001','Female Open','C');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10001','50+ Male','R');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10001','50+ Male','C');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10001','Under 21 Male','B');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10001','Under 21 Female','R');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10001','Under 21 Female','C');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10001','Under 18 Male','R');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10001','Under 18 Male','C');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','Male Open','L');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','Female Open','B');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','50+ Male','B');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','50+ Female','R');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','50+ Female','C');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','50+ Female','B');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','60+ Male','R');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','60+ Male','C');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','60+ Male','B');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','70+ Male','R');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','70+ Male','C');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','70+ Male','B');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','Under 21 Male','L');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','Under 21 Female','B');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','Under 18 Male','R');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','Under 18 Male','C');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','Under 18 Male','B');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','Under 18 Female','R');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10002','Under 18 Female','C');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','Male Open','L');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','Female Open','L');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','50+ Male','L');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','50+ Female','L');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','60+ Male','L');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','60+ Female','R');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','60+ Female','C');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','60+ Female','B');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','60+ Female','L');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','70+ Male','L');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','60+ Female','R');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','60+ Female','C');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','60+ Female','B');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','60+ Female','L');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','Under 21 Female','L');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','Under 18 Male','L');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','Under 18 Female','B');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','Under 18 Female','L');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','Under 16 Male','R');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','Under 16 Male','C');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','Under 16 Female','R');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10003','Under 16 Female','C');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10010','Under 16 Male','B');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10010','Under 16 Male','L');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10010','Under 16 Female','B');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10010','Under 16 Female','L');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10010','Under 14 Male','R');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10010','Under 14 Male','C');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10010','Under 14 Male','B');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10010','Under 14 Male','L');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10010','Under 14 Female','R');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10010','Under 14 Female','C');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10010','Under 14 Female','B');
INSERT INTO DefaultEquipment(RoundID, Category, Equipment) VALUES ('10010','Under 14 Female','L');
