INSERT INTO Rounds (RoundName, TotalArrows, TotalPossibleScores) VALUES ('WA90/1440', '144', '1440');
INSERT INTO Rounds (RoundName, TotalArrows, TotalPossibleScores) VALUES ('WA70/1440', '144', '1440');
INSERT INTO Rounds (RoundName, TotalArrows, TotalPossibleScores) VALUES ('WA60/1440', '144', '1440');
INSERT INTO Rounds (RoundName, TotalArrows, TotalPossibleScores) VALUES ('AA50/1440', '144', '1440');
INSERT INTO Rounds (RoundName, TotalArrows, TotalPossibleScores) VALUES ('AA40/1440', '144', '1440');
INSERT INTO Rounds (RoundName, TotalArrows, TotalPossibleScores) VALUES ('Long Sydney','120','1200');
INSERT INTO Rounds (RoundName, TotalArrows, TotalPossibleScores) VALUES ('Sydney','120','1200');
INSERT INTO Rounds (RoundName, TotalArrows, TotalPossibleScores) VALUES ('Long Brisbane','120','1200');
INSERT INTO Rounds (RoundName, TotalArrows, TotalPossibleScores) VALUES ('Brisbane','120','1200');
INSERT INTO Rounds (RoundName, TotalArrows, TotalPossibleScores) VALUES ('Adelaide','120','1200');
INSERT INTO Rounds (RoundName, TotalArrows, TotalPossibleScores) VALUES ('Short Adelaide','120','1200');
INSERT INTO Rounds (RoundName, TotalArrows, TotalPossibleScores) VALUES ('Hobart','90','900');
INSERT INTO Rounds (RoundName, TotalArrows, TotalPossibleScores) VALUES ('Perth','90','900');